# Copyright (c) 2026 Tax Policy Associates Ltd
# Released under the MIT Licence. See LICENCE in the project root.
"""Model parameters, paths and sources. Modelling assumptions are separate from tax rules."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

# Where things live
PROJECT_ROOT = Path(__file__).resolve().parents[2]

DOCS = PROJECT_ROOT / "docs"
HMRC_DIR = DOCS / "hmrc"
ONS_DIR = DOCS / "ons"
WAS_DIR = DOCS / "was"

# Keep generated data separate from source evidence.
BUILD = PROJECT_ROOT / ".tmp" / "build"
OUTPUT = PROJECT_ROOT / "code" / "output"

for _d in (BUILD, OUTPUT):
    _d.mkdir(parents=True, exist_ok=True)

# Source files
LIFE_TABLES_XLSX = ONS_DIR / "nltew_1980_2023_single_year_life_tables.xlsx"
# Generated by acquire/price_indices.py.
HOUSE_PRICE_INDEX = BUILD / "house_price_index.csv"
CPI_INDEX = BUILD / "cpi.csv"
UPRATING_JSON = BUILD / "uprating.json"
FERTILITY_XLSX = ONS_DIR / "cohort_fertility_2024_reference_table.xlsx"
POPULATION_XLSX = ONS_DIR / "uk_population_mid2024.xlsx"
POPULATION_PROJECTIONS_XLSX = ONS_DIR / "uk_population_projections_2024based.xlsx"
WAS_AGGREGATE_XLSX = ONS_DIR / "was_total_wealth_tables_r8.xlsx"

HMRC_TABLE = {
    "12.1": HMRC_DIR / "table_12_1_final.ods",   # numbers and tax by estate size
    "12.2": HMRC_DIR / "table_12_2_final.ods",   # exemptions and reliefs
    "12.3": HMRC_DIR / "table_12_3_final.ods",   # assets by estate size
    "12.4": HMRC_DIR / "table_12_4_final.ods",   # assets by age, sex, marital status
    "12.5": HMRC_DIR / "table_12_5_final.ods",   # as 12.4, taxpaying estates only
    "12.8": HMRC_DIR / "table_12_8_final.ods",   # tax by region
    "12.9": HMRC_DIR / "table_12_9_final.ods",   # liable estates by constituency
}

# The question we are asking
# Use 65 as the age cutoff; test 70 and 75 in sensitivity runs.
AGE_THRESHOLDS = (65, 70, 75)
HEADLINE_AGE = 65

# Tax thresholds in pounds. A £10,000 bill means £25,000 above the tax-free bands.
LIABILITY_THRESHOLDS = (0.0, 10_000.0, 100_000.0)

# Liability bands: zero, then lower bounds in pounds.
BILL_BANDS = (0.0, 10_000.0, 50_000.0, 100_000.0, 200_000.0, 500_000.0)
BILL_BAND_LABELS = ("No inheritance tax", "Up to £10,000", "£10,000 to £50,000",
                    "£50,000 to £100,000", "£100,000 to £200,000",
                    "£200,000 to £500,000", "£500,000 or more")

# An "adult" child, for counting who has a stake.
ADULT_AGE = 18

# Align population, cohorts and property values with the April 2027 rules.
MODEL_YEAR = 2027
MODEL_DATE = "2027-04"

# Uprate wealth from the average over the WAS round 8 fieldwork window.
SURVEY_WINDOW = ("2020-04", "2022-03")

# The tax year we validate against. Prices are re-based to it before the
# comparison, otherwise part of the model/HMRC gap is just four years of
# inflation rather than anything real about estates.
VALIDATION_WINDOW = ("2023-04", "2024-03")

# Project ONS mid-2024 population estimates to the model year.
POPULATION_BASE_YEAR = 2024
POPULATION_YEAR = MODEL_YEAR

# Inheritance tax rules
@dataclass(frozen=True)
class RuleSet:
    """Tax rules for one year. The headline uses 2027-28, including unused pension funds."""

    name: str

    # Per-person nil-rate band, frozen from April 2009 to April 2031.
    nil_rate_band: float = 325_000.0

    # Residence band, capped at the home value passing to direct descendants.
    residence_nil_rate_band: float = 175_000.0

    # Withdraw £1 of residence band per £2 above the taper threshold.
    rnrb_taper_threshold: float = 2_000_000.0
    rnrb_taper_rate: float = 0.5

    # Flat rate above the available bands.
    rate: float = 0.40

    # From April 2026: 100% APR/BPR on the first £2.5m, 50% above. Unused allowance transfers between spouses.
    # https://www.gov.uk/government/publications/changes-to-agricultural-property-relief-and-business-property-relief/agricultural-property-relief-and-business-property-relief-changes
    apr_bpr_allowance: float = 2_500_000.0
    apr_bpr_relief_above_allowance: float = 0.50

    # Include unused DC pension funds from 6 April 2027.
    pensions_in_estate: bool = False


RULES_2026_27 = RuleSet(name="2026-27 (pensions outside the estate)",
                        pensions_in_estate=False)

RULES_2027_28 = RuleSet(name="2027-28 (pensions inside the estate)",
                        pensions_in_estate=True)

# 2023-24 rules for validation: uncapped business relief, pensions excluded.
RULES_2023_24 = RuleSet(
    name="2023-24 (validation target)",
    apr_bpr_allowance=float("inf"),
    apr_bpr_relief_above_allowance=1.0,
    pensions_in_estate=False,
)

HEADLINE_RULES = RULES_2027_28

# Modelling choices, as opposed to legislated facts
@dataclass(frozen=True)
class ModelAssumptions:
    """Modelling assumptions and sensitivity settings."""

    # Discount WAS replacement-cost physical wealth to probate resale values. Checked against HMRC movable property in validate.py.
    physical_wealth_haircut: float = 0.35

    # Survey money is not model-date money. Fieldwork ran to March 2022; the rules take effect in April 2027. None means use the factor acquire/price_indices.py measured, a number overrides it for a sensitivity run.
    # Property moves on the Great Britain house price index.
    uprate_property: float | None = None

    # Savings and pension pots move on CPI, which rose about 31% between the fieldwork and April 2027. This is the exchange rate between survey money and model-date money, not a forecast of any household's portfolio.
    uprate_financial: float | None = None
    uprate_pension: float | None = None

    # Possessions are held at their survey values. They enter as what it would cost to replace them, and second-hand furniture and cars do not follow an index driven by energy and food; they also wear out. Setting this to None puts them on CPI with everything else, which is a sensitivity rather than the base case.
    uprate_physical: float | None = 1.0

    # WAS misses the wealthiest households. Pareto-tail correction: Advani, Bangham and Leslie (Fiscal Studies, 2021). This should affect total tax much more than the exposed share.
    apply_pareto_tail: bool = True
    pareto_alpha: float = 1.65
    pareto_threshold: float = 2_000_000.0

    # Allow for widows whose late spouse used some of their nil-rate band.
    widow_transferred_band_share: float = 0.95

    # Test whether family size varies with wealth.
    children_wealth_correlation: float = 0.0

    # "observed" uses survey DC pots; "cohort_shifted" borrows the profile five years younger as an upper bound. The age gap mixes cohort differences with retirement drawdown.
    pension_cohort_basis: str = "observed"

    # Two allowances for unmarried couples assumes equal ownership. Test one allowance as a sensitivity.
    cohabiting_band_sets: float = 2.0

    # Person weighting uses each member's age. Household weighting puts everyone in the oldest member's band.
    post_stratify_per_person: bool = True

    # Which year's population the weights are raked to. The headline model is April 2027, so it uses the projection for 2027. Validation overrides this to the year HMRC's outturn covers, for the same reason it re-bases prices: the 65-plus population grows 6% over those three years, and counting that as evidence about decumulation would be wrong twice over.
    population_year: int = POPULATION_YEAR

    # Include households with more than two adults; assign wealth to senior members. Exclusion redistributes their weight to other households. See experiments/multi_generational/composition.py.
    exclude_multi_generational: bool = False

    # Asset definitions: model/business_property.py. Relief checks: model/calibrate_reliefs.py.
    include_business_agricultural: bool = True

    # Rank survey holders by reported value and map them to HMRC's claim distribution (model/relief_distribution.py). Assumes living holders and claims at death have the same distribution shape; keeps all holders.
    remap_to_published_distribution: bool = True

    # Home valuation: "none" uses current value, "nominal" uses purchase cost, "real" uses inflation-adjusted cost. See model/housing_gain.py.
    housing_gain_counterfactual: str = "none"

    # Cap survey business values at the 99th percentile to limit outliers. Mainly affects runs without HMRC remapping.
    business_winsorise_percentile: float = 99.0


ASSUMPTIONS = ModelAssumptions()

# Validation targets, straight from HMRC table 12.1 for 2023-24
VALIDATION_2023_24 = {
    "taxpaying_estates": 30_400,
    "total_tax_gbp": 7.03e9,
    "total_uk_deaths": 644_000,
    "proportion_taxed_pct": 4.72,
}

# Validation tolerances; the headline count has the tightest limit.
VALIDATION_TOLERANCE = {
    "taxpaying_estates": 0.10,
    "total_tax_gbp": 0.15,
}

# Relief claims at death, from HMRC table 12.2b and 12.2c for 2023-24
# Uncapped 2023-24 relief claims approximate qualifying property values. Counts cover estates above the nil-rate band that filed a return.

RELIEF_CLAIMS_2023_24: dict[str, dict] = {
    "agricultural": {
        "claims": 2_141,
        "value_gbp": 2.114e9,
        # Each tuple is (band lower limit, claim count, total relief). Use the mean for the open top band.
        "bands": [(0, 654, 71e6), (250_000, 413, 144e6), (500_000, 428, 294e6),
                  (1_000_000, 480, 752e6), (2_500_000, 109, 338e6),
                  (5_000_000, 57, 515e6)],
    },
    "business": {
        "claims": 4_062,
        "value_gbp": 3.853e9,
        "bands": [(0, 2_212, 190e6), (250_000, 712, 257e6),
                  (500_000, 515, 363e6), (1_000_000, 344, 527e6),
                  (2_500_000, 169, 593e6), (5_000_000, 109, 1_924e6)],
    },
}

# Allow for HMRC's rounding to three significant figures.
for _asset, _spec in RELIEF_CLAIMS_2023_24.items():
    _n = sum(n for _, n, _ in _spec["bands"])
    _v = sum(v for _, _, v in _spec["bands"])
    assert abs(_n - _spec["claims"]) <= 5, f"{_asset}: band counts sum to {_n}"
    assert abs(_v - _spec["value_gbp"]) / _spec["value_gbp"] < 0.01, \
        f"{_asset}: band values sum to {_v}"
